# Generated by Django 4.1.7 on 2023-05-18 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bloc', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personnel',
            name='user',
        ),
        migrations.RemoveField(
            model_name='project',
            name='name',
        ),
        migrations.RemoveField(
            model_name='service',
            name='name',
        ),
        migrations.AddField(
            model_name='personnel',
            name='lien_profil',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='personnel',
            name='name',
            field=models.CharField(default=' ', max_length=100),
        ),
        migrations.AddField(
            model_name='personnel',
            name='prenom',
            field=models.CharField(default=' ', max_length=100),
        ),
        migrations.AddField(
            model_name='project',
            name='achevé',
            field=models.CharField(choices=[('O', 'On cours '), ('N', 'Non')], default='O', max_length=1),
        ),
        migrations.AddField(
            model_name='project',
            name='libellai',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='service',
            name='type',
            field=models.CharField(choices=[('CHG', 'Charte graphique'), ('O3D', 'Objet 3D'), ('SCE', 'Scénarisation')], default='CHG', max_length=3),
        ),
        migrations.AlterField(
            model_name='detail',
            name='file',
            field=models.FileField(upload_to='project_files/'),
        ),
        migrations.AlterField(
            model_name='service',
            name='description',
            field=models.TextField(default='Non définie'),
        ),
    ]
