# Generated by Django 4.1.7 on 2023-05-22 06:46

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bloc', '0002_remove_personnel_user_remove_project_name_and_more'),
    ]

    operations = [
       migrations.AddField(
    model_name='project',
    name='date_debut',
    field=models.DateField(default=datetime.datetime(2023, 1, 1), verbose_name='Date début'),
    preserve_default=False,
        ),
       migrations.AddField(
    model_name='project',
    name='date_fin',
    field=models.DateField(default=datetime.datetime(2023, 12, 31), verbose_name='Date fin'),
    preserve_default=False,
     ),

       migrations.AddField(
    model_name='project',
    name='pourcentage',
    field=models.IntegerField(default=0, verbose_name='Pourcentage'),
    preserve_default=False,
),

        migrations.CreateModel(
            name='Tache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(default=' ', max_length=100)),
                ('description', models.TextField(default='Non définie')),
                ('date_depot', models.DateField(blank=True, null=True)),
                ('Img', models.ImageField(blank=True, null=True, upload_to='media/')),
                ('personne', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bloc.personnel')),
                ('projet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bloc.project')),
            ],
        ),
    ]
