# Generated by Django 4.1.7 on 2023-05-22 10:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bloc', '0004_remove_project_date_debut_remove_project_date_fin'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='date_debut',
            field=models.DateField(default=datetime.date.today, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='date_fin',
            field=models.DateField(blank=True, null=True),
        ),
    ]
