# Generated by Django 4.1.7 on 2023-05-22 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bloc', '0005_project_date_debut_project_date_fin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='date_debut',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='date_fin',
            field=models.DateField(null=True),
        ),
    ]
