# Generated by Django 4.1.7 on 2023-05-22 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bloc', '0006_alter_project_date_debut_alter_project_date_fin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='pourcentage',
        ),
    ]
