# Generated by Django 4.1.7 on 2023-05-22 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bloc', '0007_remove_project_pourcentage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='date_debut',
            field=models.DateField(default='YYYY-MM-DD', null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='date_fin',
            field=models.DateField(default='YYYY-MM-DD', null=True),
        ),
    ]
