# Generated by Django 4.1.7 on 2023-05-22 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bloc', '0010_rename_date_debut_project_datedebut_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='pourcentage',
            field=models.CharField(default='0 %', max_length=255),
        ),
    ]
