# Generated by Django 4.1.7 on 2023-05-22 10:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bloc', '0011_project_pourcentage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='pourcentage',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(100)]),
        ),
    ]
