# Generated by Django 4.1.7 on 2023-05-22 11:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bloc', '0012_alter_project_pourcentage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='pourcentage',
        ),
    ]
