# Generated by Django 4.2.1 on 2023-05-22 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bloc', '0013_remove_project_pourcentage'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='image',
            field=models.ImageField(default='media/portfolio_images/rr.jpg', upload_to='portfolio_images/'),
        ),
        migrations.AddField(
    model_name='project',
    name='pourcentage',
    field=models.IntegerField(default=0, verbose_name='Pourcentage'),
    preserve_default=False,
),

    ]
