# Generated by Django 4.2.1 on 2023-05-22 18:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('bloc', '0014_project_image_project_pourcentage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='datedebut',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='project',
            name='datefin',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
