# Generated by Django 4.2.1 on 2023-05-22 18:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bloc', '0017_alter_project_datefin'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='datedebut',
            new_name='date_debut',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='datefin',
            new_name='date_fin',
        ),
    ]
