# Generated by Django 4.2.1 on 2023-05-22 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bloc', '0018_rename_datedebut_project_date_debut_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='date_debut',
            field=models.DateField(null=True),
        ),
    ]
