# Generated by Django 4.2.1 on 2023-05-22 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bloc', '0020_alter_project_pourcentage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='pourcentage',
            field=models.IntegerField(default=0),
        ),
    ]
