# Generated by Django 4.1.7 on 2023-05-22 21:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bloc', '0021_alter_project_pourcentage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='image',
        ),
    ]
